services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: x_flask
    depends_on:
      - mysql
      - redis
    ports:
      - 80:80
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    container_name: x_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: company
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    container_name: x_redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: x_phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8080:80


  # Til DB eksamen
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db


volumes:
  mysql_data:
  redis_data:
  mongodb_data: #db eksamen
